services:
  ip-monitor:
    build: .
    container_name: ip_monitor
    restart: unless-stopped
    volumes:
      - ip_data:/data
    environment:
      # Intervalo de checagem em minutos
      - CHECK_INTERVAL_MINUTES=1440

      # Modo de entrega: 'Smtp' (padrão) ou 'DirectMx'
      - EMAIL_DELIVERY_MODE=Smtp

      # Obrigatório se EMAIL_DELIVERY_MODE=Smtp
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=ip-monitor@gmail.com
      - SMTP_PASS=0123456789abcdef

      # Obrigatório em todos os modos
      - EMAIL_FROM=ip-monitor@gmail.com
      - EMAIL_TO=your-mail@gmail.com,another@gmail.com

volumes:
  ip_data:
